baseurl: "/cmt-redisigned"
defaults:
  - scope:
      path: "sermons"
    values:
      layout: "sermons"
      node: "Sermons"

  - scope:
      path: "sermons/2020"
    values:
      year: "2020"

  - scope:
      path: "sermons/2021"
    values:
      year: "2021"

  - scope:
      path: "sermons/2020/sunday"
    values:
      layout: "sermon"
  
  - scope:
      path: "sermons/2021"
    values:
      layout: "sermon"

  - scope:
      path: "sermons/2020/thursday"
    values:
      layout: "sermon"

  - scope:
      path: "sermons/2019"
    values:
      year: "2019"

  - scope:
      path: "sermons/2019/sunday"
    values:
      layout: "sermon"

  - scope:
      path: "sermons/2019/thursday"
    values:
      layout: "sermon"

  - scope:
      path: "sermons/2018/thursday"
    values:
      layout: "sermon"

  - scope:
      path: "teachings/articles"
    values:
      layout: "teaching"
      node: "Teachings"

  - scope:
      path: "music"
    values:
      layout: "music"
      node: "Music"
